### ISSUE TITLE
How to set the mid_epochs and gamma for a new dataset?

### ISSUE THREAD

**Issue by whuhxb** [lnsmith54/CFL#6]
Hi @lnsmith54 , 

   Do you know how to set the mid_epochs if the total train epoch is 600. And, how to tune the gamma for a new dataset? Setting as 1, 2, 3, 4 to test? Do you have any experience or suggestion?
   Best wishes.

Xiaobing

**Comment by lnsmith54** [comment]
As I described in my paper at https://arxiv.org/pdf/2202.08978.pdf, by default I used f_c = 4.  In addition, I tested gamma_hc = 2 and 3 when deciding which gamma to use.  If you don't want to tune gamma, just set it to 2.  

You can find much more information in my papers.  I've updated my README to link to both papers.

Best wishes,
Leslie

**Comment by whuhxb** [comment]
> As I described in my paper at https://arxiv.org/pdf/2202.08978.pdf, by default I used f_c = 4. In addition, I tested gamma_hc = 2 and 3 when deciding which gamma to use. If you don't want to tune gamma, just set it to 2.
> 
> You can find much more information in my papers. I've updated my README to link to both papers.
> 
> Best wishes, Leslie

Hi @lnsmith54 

If the total epoch is 600, how to set the hyperparameter of mid epoch? Thanks again.

**Comment by lnsmith54** [comment]
On the command line, include this input argument:
`--cyclical_factor 4`
This will set the mid epoch as 200.

**Comment by whuhxb** [comment]
> On the command line, include this input argument: `--cyclical_factor 4` This will set the mid epoch as 200.

For my own dataset, the cyclical_factor is also set to 4, and mid epoch is also set to 200, right? Should these be tuned? What means for cyclical_factor as 4?

**Comment by lnsmith54** [comment]
I suggest you look at my paper "General Cyclical Training of Neural Networks" at https://arxiv.org/pdf/2202.08835 for a Figure and and description of the cyclical_factor.
